apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudflare-operator.fullname" . }}-accessapplication-editor
  labels:
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["cloudflare.k8stooling.io"]
    resources: [accessapplications]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: ["cloudflare.k8stooling.io"]
    resources: [accessapplications/status]
    verbs: [get]
