apiVersion: cloudflare.k8stooling.io/v1alpha1
kind: AccessApplication
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: accessapplication-sample
spec:
  # TODO(user): Add fields here
